// Pulls the webfonts off Google's CDN once, into the repo, so the running site
// never talks to fonts.googleapis.com / fonts.gstatic.com.
//
//   npm run fonts
//     -> public/fonts/*.woff2      committed, served same-origin
//     -> src/styles/fonts.css      committed, @imported by global.css
//
// The hosted stylesheet is render-blocking on a third-party origin: the browser
// pays DNS + TLS + CSS before it even learns which font files it needs. Serving
// them ourselves collapses that into one already-warm connection, and lets us
// preload the two faces the first paint actually uses.
//
// Rerun this only when the font list below changes. Both families are OFL.

import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const OUT_DIR = 'public/fonts';
const OUT_CSS = 'src/styles/fonts.css';

// Weights actually used in the stylesheets — keep in sync, every extra weight is
// two more files. Content carries Polish names (ą, ł, ń), hence latin-ext.
const FAMILIES = 'family=Hanken+Grotesk:wght@400;500;600&family=Spectral:ital,wght@0,300;0,400;0,500;0,600;1,400';
const SUBSETS = ['latin', 'latin-ext'];

// Google serves woff2-only CSS to modern browsers and a woff/ttf fallback to
// anything else, so ask as Chrome.
const UA =
	'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';

const css = await fetch(`https://fonts.googleapis.com/css2?${FAMILIES}&display=swap`, {
	headers: { 'User-Agent': UA },
}).then((res) => {
	if (!res.ok) throw new Error(`Google Fonts responded ${res.status}`);
	return res.text();
});

// Each face arrives as a `/* <subset> */` comment followed by its @font-face block.
const blocks = [...css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
if (blocks.length === 0) throw new Error('Could not parse any @font-face blocks');

await mkdir(OUT_DIR, { recursive: true });

const rules = [];

for (const [, subset, block] of blocks) {
	if (!SUBSETS.includes(subset)) continue;

	const field = (name) => block.match(new RegExp(`${name}:\\s*([^;]+);`))?.[1].trim();
	const family = field('font-family')?.replace(/['"]/g, '');
	const weight = field('font-weight');
	const style = field('font-style');
	const range = field('unicode-range');
	const url = block.match(/url\((https:[^)]+)\)/)?.[1];
	if (!family || !weight || !style || !url) throw new Error(`Incomplete @font-face block:\n${block}`);

	const slug = family.toLowerCase().replace(/\s+/g, '-');
	const file = `${slug}-${weight}${style === 'italic' ? '-italic' : ''}-${subset}.woff2`;

	const body = await fetch(url, { headers: { 'User-Agent': UA } });
	if (!body.ok) throw new Error(`${url} responded ${body.status}`);
	await writeFile(join(OUT_DIR, file), Buffer.from(await body.arrayBuffer()));

	rules.push(
		[
			`/* ${subset} */`,
			'@font-face {',
			`\tfont-family: '${family}';`,
			`\tfont-style: ${style};`,
			`\tfont-weight: ${weight};`,
			// swap, not the CDN's default: text must be readable while the face loads.
			'\tfont-display: swap;',
			`\tsrc: url('/fonts/${file}') format('woff2');`,
			...(range ? [`\tunicode-range: ${range};`] : []),
			'}',
		].join('\n'),
	);

	console.log(`${file}`);
}

const header = `/* Generated by scripts/fetch-fonts.mjs - do not edit by hand. */\n\n`;
await writeFile(OUT_CSS, header + rules.join('\n\n') + '\n');

console.log(`\n${rules.length} faces -> ${OUT_DIR}, ${OUT_CSS}`);
